[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
sol_medicine = "7KkA5mE2J3VJqbAKsSVicajny9VGXStDNtefbxCCbjjM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
